JamieSinn/CSA-USB-Tool

Software2019.csv
Added a zip file on our server with all the software for the SPARK MAX.
=> Adds REV SPARK MAX for 2019

Software2019.csv
Update CTRE installer to 5.14.0
Update VSCode C++ plugin to 0.21.0 to match WPILib 2019.3.2
Add PCM firmware version 1.65 and PDP firmware 1.40
=> Update CTRE and VSCode-CPP.

Software2019.csv
https://github.com/wpilibsuite/allwpilib/releases/tag/v2019.4.1
=> Updating WPILib to 2019.4.1

Software2019.csv
Firmware hotfix update to v1.1.33 for SPARK MAX
=> Adds updated firmware for SPARK MAX and drivers for PC Client

Software2019.csv
May or may not work on different IPs, depends how NI servers work
=> Updated with latest version of dashboard link

appveyor.yml
This should fix the build errors in appveyor.
=> Change appveyor.yml to use 2017 Visual Studio for build.

FRCSoftware2020.csv
=> Update NI to offline installers and add 7-zip to extract iso

FRCSoftware2020.csv
Perhaps the app should trim whitespace when parsing the CSV... Either way, it was bothering me, so I fixed the CSV
=> Remove excess space in filename

FRCSoftware2019.csv, FRCSoftware2020.csv
Caused by https://github.com/microsoft/vscode/issues/119822
=> Update broken VSCode download URL

CSAUSBTool/CSAUSBTool.cs
=> Enable multi-selection for file list

FRCSoftware2022.csv
Teams will need to use this image at events. Thanks!
=> Add limelight 2022.2.2 image

FRCSoftware2022.csv
https://www.chiefdelphi.com/t/dslog-reader-2-2-driver-station-log-viewer-with-more-features/405040
=> Adds latest version of 3rd party log reader DSLOG Reader 2.2

FRCSoftware2022.csv
CTRE 5.21.2
REV LabVIEW 2022.1.2
REV Hardware Client 1.4.3
Limelight 2022.2.3
=> Update for mid-season vendor updates

FRCSoftware2023.csv
Adds:
- Latest Firmware zip
- Tuner X Offline installer
- Linux offline zip
- macOS offline zip
- v5 docs pdf
- pro docs pdf
=> Update CTR Resources for 2023

FRCSoftware2023.csv
Add Limelight 3 link also.
Fixes #75
=> Update Limelight for 2023

README.md, pyusbtool.py
First off, having all of these files in a single place has been really useful over the years, so thank you for putting in the work to make this tool!
I don't use Windows at home at all these days, so using your tool is fairly challenging for me. Since the task at hand is just downloading files, I wrote a python script that does the same job. It's not the prettiest, but it gets the job done.
=> Add python script to download files

FRCSoftware2023.csv
=> Add SPARK MAX firmware

FRCSoftware2023.csv
Also shortens the friendly name so that it fits. Current screenshot:
=> Fix FRC REV Hardware Client download link

README.md, pyusbtool.py
Improves clarity of `pyusbtool.py` usage for newcomers
=> small pyusbtool doc improvements

FRCSoftware2024.csv
Update FRCSoftware2024.csv for Game Tools 24.0.2
=> Update FRCSoftware2024.csv for Game Tools 24.0.2

FRCSoftware2024.csv
Also remove out-of-date navx offline zip
=> Update revlib offline to 2024.2.2

Lists/FRC2025.json
Reverts JamieSinn/CSA-USB-Tool#132
=> Revert "Set platform independent files platform to null"

CSAUSBTool.CrossPlatform/Models/ControlSystemSoftware.cs, CSAUSBTool.CrossPlatform/Models/ControlSystemSoftwareGroup.cs, CSAUSBTool.CrossPlatform/Views/ControlSystemSoftwareGroupView.axaml, CSAUSBTool.CrossPlatform/Views/ControlSystemSoftwareGroupView.axaml.cs, CSAUSBTool.CrossPlatform/Views/ControlSystemSoftwareView.axaml, CSAUSBTool.CrossPlatform/Views/MainWindow.axaml, CSAUSBTool.CrossPlatform/Views/ProgramYearView.axaml
=> Update UX layout to fit inside the Window (instead of resizing Window to match layout)
